FROM golang:1.21
WORKDIR /app
ADD . .
ENV CGO_ENABLED=0
RUN cd ./youtube-bot && go mod download
RUN go build -o main ./youtube-bot/*.go

FROM ubuntu:focal
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y ca-certificates google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
COPY --from=0 ./app/main .
EXPOSE 4000
CMD [ "/main" ]