FROM golang:1.21
WORKDIR /app
ADD . .
ENV CGO_ENABLED=0
RUN cd ./image-bot && go mod download
RUN go build -o main ./image-bot/*.go

FROM scratch
COPY --from=0 ./app/main .
EXPOSE 4000
CMD [ "/main" ]